# Generated by Django 5.2.5 on 2025-10-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("COMERCIAL", "Usuario Comercial"),
                    ("CONSTRUCTOR", "Usuario Constructor"),
                    ("JEFE", "Jefe"),
                ],
                default="COMERCIAL",
                max_length=32,
            ),
        ),
    ]
