# Generated by Django 5.2.5 on 2025-09-02 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0002_unitprice_project_acabado_muros_project_acceso_obra_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del rol"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del trabajador"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("cedula", models.CharField(max_length=20, verbose_name="Cédula")),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.worker",
                verbose_name="Trabajadores asignados",
            ),
        ),
    ]
