# Generated by Django 5.2.5 on 2025-09-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_role_worker_project_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="salario_base_dia",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Salario base por día (COP)",
            ),
        ),
    ]
