# Generated by Django 5.1.6 on 2025-09-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_role_salario_base_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del material')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='EntradaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad ingresada')),
                ('lote', models.CharField(max_length=50, verbose_name='Número de lote')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_materiales', to='projects.project', verbose_name='Proyecto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='projects.material', verbose_name='Material')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de material',
                'verbose_name_plural': 'Entradas de materiales',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
