# Generated by Django 5.1.6 on 2025-09-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_materialsupplier_lead_time_days'),
        ('projects', '0005_material_proveedor_entradamaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='catalog.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='entradamaterial',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
