# Generated by Django 5.1.6 on 2025-09-03 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_material_stock'),
        ('projects', '0006_alter_entradamaterial_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_proyecto', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock asignado al proyecto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='catalog.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='projects.project')),
            ],
            options={
                'unique_together': {('proyecto', 'material')},
            },
        ),
    ]
