# Generated by Django 5.1.6 on 2025-09-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_proyectomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaterial',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='projects.project', verbose_name='Proyecto'),
        ),
    ]
