# Generated by Django 5.2.5 on 2025-10-08 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_material_stock"),
        ("projects", "0008_alter_entradamaterial_proyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_consumida",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Cantidad del material que se consumió",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Cantidad consumida",
                    ),
                ),
                (
                    "fecha_consumo",
                    models.DateField(
                        help_text="Fecha en la que se usó el material",
                        verbose_name="Fecha de consumo",
                    ),
                ),
                (
                    "componente_actividad",
                    models.CharField(
                        help_text="Ej: Cimentación, Muros primer piso, Instalación eléctrica",
                        max_length=200,
                        verbose_name="Componente/Actividad",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        help_text="Nombre de la persona responsable del uso del material",
                        max_length=200,
                        verbose_name="Responsable del uso",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el consumo (opcional)",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se registró este consumo en el sistema",
                        verbose_name="Fecha de registro",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="catalog.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        help_text="Usuario que registró este consumo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de material",
                "verbose_name_plural": "Consumos de materiales",
                "ordering": ["-fecha_consumo", "-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["proyecto", "fecha_consumo"],
                        name="projects_co_proyect_03e997_idx",
                    ),
                    models.Index(
                        fields=["material", "fecha_consumo"],
                        name="projects_co_materia_83bf4c_idx",
                    ),
                ],
            },
        ),
    ]
