# Generated by Django 5.2.5 on 2025-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_consumomaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumomaterial",
            name="responsable",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la persona responsable del uso del material",
                max_length=200,
                verbose_name="Responsable del uso",
            ),
        ),
    ]
