# Generated by Django 5.2.5 on 2025-10-09 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_consumomaterial_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la sección"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_percentage",
                    models.BooleanField(default=False, verbose_name="Es porcentual"),
                ),
                (
                    "percentage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Para secciones como Administración (12%)",
                        max_digits=5,
                        verbose_name="Valor porcentual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Presupuesto",
                "verbose_name_plural": "Secciones de Presupuesto",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Código"),
                ),
                ("description", models.TextField(verbose_name="Descripción del ítem")),
                ("unit", models.CharField(max_length=20, verbose_name="Unidad")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio Unitario (COP)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden en sección"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.budgetsection",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Presupuesto",
                "verbose_name_plural": "Ítems de Presupuesto",
                "ordering": ["section__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.budgetitem",
                        verbose_name="Ítem de Presupuesto",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="projects.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Presupuesto del Proyecto",
                "verbose_name_plural": "Ítems de Presupuesto del Proyecto",
                "unique_together": {("project", "budget_item")},
            },
        ),
    ]
