# Generated by Django 5.1.6 on 2025-10-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_budgetsection_budgetitem_projectbudgetitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ubicacion_proyecto',
            field=models.CharField(choices=[('Medellin', 'Medellín'), ('Bogota', 'Bogotá'), ('Cali', 'Cali'), ('Otra', 'Otra (especificar)')], default='medellin', max_length=20, verbose_name='Ubicación del proyecto'),
        ),
    ]
