# Generated by Django 5.1.6 on 2025-10-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_ubicacion_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by_ai',
            field=models.BooleanField(default=False, help_text='Indica si este proyecto fue generado automáticamente por el chatbot IA', verbose_name='Creado por IA'),
        ),
    ]
