# Generated by Django 5.1.6 on 2025-10-13 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_created_by_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doors_height',
            field=models.DecimalField(decimal_places=2, default=2.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura de las puertas (en metros)'),
        ),
    ]
