# Generated by Django 5.2.5 on 2025-10-29 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_project_doors_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetsection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_sections",
                to="projects.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
