# Generated by Django 5.1.6 on 2025-10-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_consumomaterial_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomaterial',
            name='etapa_presupuesto',
            field=models.ForeignKey(help_text='Etapa/categoría del presupuesto detallado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_materiales', to='projects.budgetsection', verbose_name='Etapa del presupuesto'),
        ),
    ]
