# Generated by Django 5.2.5 on 2025-10-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_budgetsection_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetsection",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_sections",
                to="projects.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
