# Generated by Django 5.2.5 on 2025-10-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_budgetsection_project"),
        ("projects", "0017_asignar_etapa_sin_categorizar"),
    ]

    operations = []
