# Generated by Django 5.2.5 on 2025-11-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_merge_20251029_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="entradamaterial",
            name="etapa_presupuesto",
            field=models.ForeignKey(
                blank=True,
                help_text="Etapa del presupuesto a la que corresponde esta compra",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas_materiales",
                to="projects.budgetsection",
                verbose_name="Etapa del presupuesto",
            ),
        ),
    ]
