# Generated by Django 5.2.5 on 2025-11-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_entradamaterial_etapa_presupuesto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entradamaterial",
            name="etapa_presupuesto",
        ),
    ]
