# Generated by Django 5.2.5 on 2025-11-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_remove_entradamaterial_etapa_presupuesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetsection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Si es NULL, es una sección plantilla global. Si tiene proyecto, es una copia para seguimiento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_sections",
                to="projects.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
