# Generated by Django 5.2.5 on 2025-11-08 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_remove_entradamaterial_etapa_presupuesto"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="administration_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                help_text="Porcentaje de administración sobre el costo directo (0-100%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje de administración",
            ),
        ),
        migrations.AlterField(
            model_name="budgetsection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Si es NULL, es una sección plantilla global. Si tiene proyecto, es una copia para seguimiento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_sections",
                to="projects.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
