# Generated by Django 5.2.5 on 2025-11-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_budgetsection_project"),
        ("projects", "0021_project_administration_percentage_and_more"),
    ]

    operations = []
