# Generated by Django 5.2.5 on 2025-11-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_merge_20251109_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="arl",
            field=models.CharField(
                default="Por asignar", max_length=100, verbose_name="ARL"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                null=True,
                verbose_name="Tipo de Sangre",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="emergency_contact_name",
            field=models.CharField(
                default="Por asignar",
                max_length=200,
                verbose_name="Nombre del Acudiente",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="emergency_contact_phone",
            field=models.CharField(
                default="Por asignar",
                max_length=20,
                verbose_name="Teléfono del Acudiente",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="eps",
            field=models.CharField(
                default="Por asignar", max_length=100, verbose_name="EPS"
            ),
        ),
    ]
