# Generated by Django 5.1.6 on 2025-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.CharField(default='idle', max_length=50),
        ),
    ]
