# Generated by Django 5.1.6 on 2025-10-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_context_conversation_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='context',
            new_name='collected_data',
        ),
        migrations.AddField(
            model_name='conversation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='flow_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('ai', 'IA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('idle', 'Inactiva'), ('manual_flow', 'Flujo Manual'), ('ai_flow', 'Flujo IA'), ('completed', 'Completada')], default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10),
        ),
    ]
