# Generated by Django 5.2.5 on 2025-08-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_supplier_materialsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsupplier',
            name='lead_time_days',
        ),
    ]
