# Generated by Django 5.1.6 on 2025-09-03 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_materialsupplier_lead_time_days'),
        
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock global disponible'),
        ),
    ]
