# Generated by Django 5.2.5 on 2025-10-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_material_stock"),
        ("catalog", "0007_stock_default_not_null"),
    ]

    operations = []
